Bac 3416 permission table test
upstars-global/cardona-core-service pull request #142
Opened 2024-12-04 19:29 UTC by SimpllleUser

2024-12-05 08:53 UTC, artem-oleinychenko commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +      :eager="IS_TEST_ENV"
@SimpllleUser а если не менять поведение компонента ради теста? или без этого прям не получится

2024-12-05 08:54 UTC, artem-oleinychenko commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +                      class="font-weight-regular text-color-base tests"
@SimpllleUser а к чему тут класс tests ?

2024-12-05 08:56 UTC, artem-oleinychenko commented on tests/unit/components/permitionsForm/GroupFragmentSettings.spec.ts
> +    /// Mac check call event and value on set state switch all
@SimpllleUser не понимаю смысл текста)

2024-12-05 08:56 UTC, artem-oleinychenko commented on tests/unit/components/permitionsForm/GroupFragmentSettings.spec.ts
> +  it('Call event on on change checkbox permission', async () => {
on on

2024-12-05 09:01 UTC, artem-oleinychenko requested changes
questions

2024-12-05 09:04 UTC, SimpllleUser commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +      :eager="IS_TEST_ENV"
Я пробовал реализовать поведение пользователя где надо сделать клик на элемент для открытия collpase это не помогло и потому реализовал таким образом

2024-12-05 09:08 UTC, SimpllleUser commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +                      class="font-weight-regular text-color-base tests"
Убрал

2024-12-05 09:08 UTC, SimpllleUser commented on tests/unit/components/permitionsForm/GroupFragmentSettings.spec.ts
> +    /// Mac check call event and value on set state switch all
Сменил

2024-12-05 09:08 UTC, SimpllleUser commented on tests/unit/components/permitionsForm/GroupFragmentSettings.spec.ts
> +  it('Call event on on change checkbox permission', async () => {
Убрал

2024-12-05 10:14 UTC, artem-oleinychenko commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +      :eager="IS_TEST_ENV"
Не может быть такого, чтобы нельзя было раскрыть элемент. Мне как и раньше не нравится, что в компонентах появляется код ради тестов. Я на странице взял элемент и методом click() он без проблем открывается
`document.querySelectorAll('.v-expansion-panel-title__icon')[2].click()`

2024-12-10 06:58 UTC, SimpllleUser commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +      :eager="IS_TEST_ENV"
Я же отписал https://github.com/upstars-global/cardona-core-service/pull/142/files#r1870947616
+ В среде jsdom он не видит ивент на onclick на селектор который ты указал 
Это было бы резонное замечане если бы я делал e2e тест

+ JSdom дом не копирует все точь-в-точь 
На этапе "Рендера" через  JSdom куча своих нюансов есть

2024-12-10 10:33 UTC, artem-oleinychenko commented on src/components/permitionsForm/GroupFragmentSettingsTable.vue
> +      :eager="IS_TEST_ENV"
🆗

2024-12-10 10:33 UTC, artem-oleinychenko approved these changes

2024-12-11 16:44 UTC, OlehMiha approved these changes

2024-12-12 11:22 UTC, merged